# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
    - echo "Listing files:"
    - ls -R
    - pwd
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Build step (optional for Node.js)"
      - grep -fq "Welcome to the Home Page" public/home.html
  post_build:
    commands:
      - echo "Ready to deploy"